### ISSUE TITLE
OpenShift is configured for server: https://127.0.0.1:8443

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-utils#101]
Not sure if 127.0.0.1 is expected in  ~/.kube/config. I think it should be only done for 10.1.2.2:8443.

```
[vagrant@rhel-cdk ~]$ oc config view
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://10.1.2.2:8443
  name: 10-1-2-2:8443
- cluster:
    certificate-authority: /var/lib/openshift/openshift.local.config/master/ca.crt
    server: https://127.0.0.1:8443
  name: 127-0-0-1:8443
contexts:
- context:
    cluster: 127-0-0-1:8443
    user: openshift-dev/127-0-0-1:8443
  name: /127-0-0-1:8443/openshift-dev
- context:
    cluster: 10-1-2-2:8443
    namespace: sample-project
    user: openshift-dev/10-1-2-2:8443
  name: sample-project/10-1-2-2:8443/openshift-dev
- context:
    cluster: 127-0-0-1:8443
    namespace: sample-project
    user: openshift-dev/127-0-0-1:8443
  name: sample-project/127-0-0-1:8443/openshift-dev
current-context: sample-project/10-1-2-2:8443/openshift-dev
kind: Config
preferences: {}
users:
- name: openshift-dev/10-1-2-2:8443
  user:
    token: 8-jTYMHcu-XFPu7GFlKe3VOsV6B8LR0r0mu_5ZWMGrw
- name: openshift-dev/127-0-0-1:8443
  user:
    token: uJNdS7ZPdOGxFPKocEHFLK1xm9M_hoeL5FHY67dhhzs
```

**Comment by praveenkumar** [comment]
@LalatenduMohanty as per config output it looks fine.

This is when user do `vagrant ssh` and try to connect with localhost. I don't see anything fishy here, @hferentschik any comment?

```
- cluster:
    certificate-authority: /var/lib/openshift/openshift.local.config/master/ca.crt
    server: https://127.0.0.1:8443
  name: 127-0-0-1:8443

contexts:
- context:
    cluster: 127-0-0-1:8443
    user: openshift-dev/127-0-0-1:8443
  name: /127-0-0-1:8443/openshift-dev
```
