### ISSUE TITLE
Should we enable incremental builds for OpenShift?

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-utils#164]
S2I can perform incremental builds, which means it reuses artifacts from previously-built images. This helps to reduce the build time of the application post the first build. For the first build process it does not work as s2i downloads required artifacts for the build. 

```
strategy:
  type: "Source"
  sourceStrategy:
    from:
      kind: "ImageStreamTag"
      name: "incremental-image:latest" 
    incremental: true  
```
